theme: jekyll-theme-cayman

comment:
  enable: false      # 是否开启配置
  owner: jangdelong  # 你的 github 账户名
  repo: blog_comments # github repository
  client_id: xxxxxxxxxx # github application client id
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # github application secret
